### ISSUE TITLE
not able install this API

### ISSUE THREAD

**Issue by sailoo121** [ericpedra/quotexapi#5]
Hi, can you tell me how to install this repo. I'm getting this error while installing
C:\>pip install git+https://github.com/ericpedra/quotexapi.git 

ERROR: git+https://github.com/ericpedra/quotexapi.git does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

Your help highly appreciated. Thanks

**Comment by renanale** [comment]
simple download it and open the paste, isn't that hard. But you might need to do some ajustments before using, which im also struggling right now.

**Comment by amir-1011** [comment]
I tried this


 1.   Clone the quotexapi repository from Github using the following command:


!git clone https://github.com/ericpedra/quotexapi.git



 2.   Navigate to the cloned directory using the following command:


cd quotexapi



3.    Install the required packages using the following command:


!pip install requests websocket-client



 4.   Create a setup.py file in the quotexapi directory with the following contents:


```
from setuptools import setup, find_packages

setup(
    name='quotexapi',
    version='0.1.0',
    packages=find_packages(),
    install_requires=[
        'requests',
        'websocket-client'
    ],
    entry_points={
        'console_scripts': [
            'quotexapi=quotexapi.__main__:main'
        ]
    }
)

```


5.    Build the quotexapi package using the following command:


!python setup.py sdist



 6.   Install the quotexapi package using the following command:


!pip install dist/quotexapi-0.1.0.tar.gz


and it worked but when ran this from quotexapi.stable_api import Quotex

It gave me this error

Traceback (most recent call last):

  File "/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File ["<ipython-input-3-364f1045d799>"](https://localhost:8080/#), line 1, in <module>
    from quotexapi.stable_api import Quotex

  File "/usr/local/lib/python3.8/dist-packages/quotexapi/stable_api.py", line 57
    """ Buy Binary option""""
                             ^
SyntaxError: EOL while scanning string literal


maybe this way was wrong


edit:

the copy paste way gives this error as well in windows

**Comment by taqveemmalik** [comment]
is there any way to install quotexAPIs?

**Comment by manoj5047** [comment]
I can install and run the library after many code corrections. Can someone please guide where can I obtain the Session id from my Quotes broker account.

**Comment by Keiiga** [comment]
> Puedo instalar y ejecutar la biblioteca después de muchas correcciones de código. ¿Puede alguien guiarme dónde puedo obtener la identificación de sesión de mi cuenta de corredor de cotizaciones?

R: With Selenium you can get your SSID, how did you manage to install the API? What corrections did you have to make? I can't install it no matter how many fixes I make.

**Comment by renanale** [comment]
Guys, forget about it. It's not complete and the owner is selling it. I had to make one by myself, not easy at all. I had to learn how to create a connection using websocket, how to maintain, how to keep pinging, and also how to awnser with the token that's needed to stabilish a connection, get the ssid. If you really want to know, start learning how to open websockets connection, how to utilize headers, and send/recieve messages without killing the thread. Now I'm also selling the feature, but just access, not source code. Took me a month to do it perfectly!

**Comment by devmexican** [comment]
Se tiene que instalar SimpleJson, pip install y hay que corregir en el archivo stable_api unas comillas en lugar de ser 3 son 4.

**Comment by devmexican** [comment]
Keiiga Puedes explicar mejor

**Comment by devmexican** [comment]
Paso el Archivo stable_api.py ---->>>>corregido

# python
from quotexapi.api import QuotexAPI
import quotexapi.global_value as global_value
import threading
import time
import logging
import operator
from collections import defaultdict
from collections import deque

def nested_dict(n, type):
    if n == 1:
        return defaultdict(type)
    else:
        return defaultdict(lambda: nested_dict(n - 1, type))

class Quotex:
    __version__ = "1.3"
    def __init__(self, set_ssid):
        self.size = [1, 5, 10, 15, 30, 60, 120, 300, 600, 900, 1800,
                    3600, 7200, 14400, 28800, 43200, 86400, 604800, 2592000]
        self.set_ssid = set_ssid
        self.suspend = 0.5
        self.subscribe_candle = []
        self.subscribe_candle_all_size = []
        self.subscribe_mood = []
        
        # --start
        # self.connect()
        # this auto function delay too long
        
        

    def change_account(self, Balance_MODE):
        """Change active account `real` or `practice`"""
        real_id = None
        practice_id = None
        if Balance_MODE == "REAL":
            pass
        elif Balance_MODE == "PRACTICE":
            pass
        else:
            logging.error("ERROR doesn't have this mode")
            exit(1)
            
    def get_balance(self):
        pass
        

    def get_balances(self):
        pass
            
    # _____________________BUY________________________________

    # __________________FOR OPTION____________________________
    def buy(self, ACTIVES, price, ACTION, expirations):
        """ Buy Binary option"""
        pass
      
    def sell_option(self, options_ids):
        pass
      
    def check_win(self, id_number):
        """Check win based id"""
        pass
      
    def get_signal_data(self):
        """ Get signal Quotex server"""
        pass
      
    def get_payment(self):
        """ payment Quotex server"""
        pass

      
      
      
    # ________________________________________________________________________
    # _______________________        CANDLE      _____________________________
    # ________________________self.api.getcandles() wss________________________
    def get_candles(self, ACTIVES, interval, offset, period):
        while True:
            try:
                pass
            except:
                logging.error('**error** get_candles need reconnect')
                self.connect() #go connect
                
    def get_candle_v2(self, ACTIVES, offset):
        while True:
            try:
                pass
            except:
                logging.error('**error** get_candle_v2 need reconnect')
                self.connect() #go connect
    # ------------------------Subscribe ONE SIZE-----------------------
    def start_candles_one_stream(self, ACTIVE, size):
        pass
    def stop_candles_one_stream(self, ACTIVE, size):
        pass
    
      
    # ------------------------Subscribe ALL SIZE-----------------------

    def start_candles_all_size_stream(self, ACTIVE):
        pass
    def stop_candles_all_size_stream(self, ACTIVE):
        pass
      
      
      
    #######################################################
    # ______________________________________________________
    # _____________________REAL TIME CANDLE_________________
    # ______________________________________________________
    #######################################################
    def start_candles_stream(self, ACTIVE, size, maxdict):

        if size == "all":
            for s in self.size:
                pass
        elif size in self.size:
            pass
        else:
            logging.error('**error** start_candles_stream please input right size')
            
    def stop_candles_stream(self, ACTIVE, size):
        if size == "all":
            pass
        elif size in self.size:
            pass
        else:
            logging.error('**error** start_candles_stream please input right size')
            
    def get_realtime_candles(self, ACTIVE, size):
        if size == "all":
            try:
                pass
            except:
                logging.error('**error** get_realtime_candles() size="all" can not get candle')
                return False
        elif size in self.size:
            try:
                pass
            except:
                logging.error('**error** get_realtime_candles() size=' + str(size) + ' can not get candle')
                return False
        else:
            logging.error('**error** get_realtime_candles() please input right "size"')
            
            
    def re_subscribe_stream(self):
        try:
            pass
        except:
            pass
        
      
      
    def connect(self):
        try:
            self.api.close()
        except:
            pass
            # logging.error('**warning** self.api.close() fail')
        self.api = QuotexAPI("quotex.market", self.set_ssid)
        check = None
        check, reason = self.api.connect()
        if check == True:
            self.re_subscribe_stream()
            return True, None
        else:
            return False, reason
          
    def close(self):
        try:
            self.api.close()
        except:
            pass
          
    def check_connect(self):
        # True/False
        # if not connected, sometimes it's None, sometimes its '0', so
        # both will fall on this first case
        if not global_value.check_websocket_if_connect:
            return False
        else:
            return True

**Comment by DiegoMotaChrist** [comment]
> I can install and run the library after many code corrections. Can someone please guide where can I obtain the Session id from my Quotes broker account.

please can you help me with the corrections you had to make

**Comment by DiegoMotaChrist** [comment]
> Guys, forget about it. It's not complete and the owner is selling it. I had to make one by myself, not easy at all. I had to learn how to create a connection using websocket, how to maintain, how to keep pinging, and also how to awnser with the token that's needed to stabilish a connection, get the ssid. If you really want to know, start learning how to open websockets connection, how to utilize headers, and send/recieve messages without killing the thread. Now I'm also selling the feature, but just access, not source code. Took me a month to do it perfectly!

dear, please help me with creating a working version, I've been in this problem for some time, trying to create and maintain a websocket connection in the python-socket-io and websocket-client libraries but without success. I participate in a VIP room with extremely assertive signals, if you can help me I will collaborate by automating the sending of signals to you in your personal telegram at no cost. I have developed a simple bot that forwards messages using python's telethon library

**Comment by DiegoMotaChrist** [comment]
guys, to get the ssid!!

<img width="434" alt="image" src="https://user-images.githubusercontent.com/41216360/231019413-4fc6a493-1b6e-40a3-92f8-078b24202305.png">
